### ISSUE TITLE
ReferenceError: debug is not defined

### ISSUE THREAD

**Issue by juanf9224** [aws-samples/amazon-cognito-passwordless-auth#174]
Hi, I'm getting an error when trying to get the magic link, it was working fine, and suddenly it started giving me that error, this is what my config looks like:

```
Passwordless.configureFromAmplify(
  Amplify.configure({
    ...awsConfig,
    region: awsConfig.aws_cognito_region,
    cognitoIdpEndpoint: awsConfig.aws_cognito_region,
    userPoolId: awsConfig.aws_user_pools_id,
    userPoolWebClientId: awsConfig.aws_user_pools_web_client_id,
  })
).with({
  fido2: {
    baseUrl: apiUrl,
    authenticatorSelection: {
      userVerification: 'required'
    },
    rp: {
      name: 'some-name,
      id: 'localhost'
    }
  },
  debug: console.debug
})
```

And this is the actual error:

```
ReferenceError: debug is not defined
    at respondToAuthChallenge (cognito-api.js:96:1)
    at eval (magic-link.js:38:47)

**Comment by juanf9224** [comment]
Closing it as the error was on our side, some debugs were added locally and it was cached.
