### ISSUE TITLE
Jest not able to mock the library on server

### ISSUE THREAD

**Issue by fahadsadiq** [aws-samples/amazon-cognito-passwordless-auth#207]
Hello @ottokruse 

I have implemented this library on back end(lambda). Following is the code that i am using:

```
import { Passwordless } from 'amazon-cognito-passwordless-auth';
import { MinimalLocation } from 'amazon-cognito-passwordless-auth/config';
export class CustomLocation implements MinimalLocation {
    private baseUrl: string = process.env.COGNITO_HOSTNAME!;
    constructor(private session: string) {}
    get href(): string {
        console.log('${this.baseUrl}#${this.session}');
        return '${this.baseUrl}#${this.session}';
    }

    get hostname(): string {
        return '${this.baseUrl}';
    }
}

export const setPasswordLess = async (session: string) => {
    Passwordless.configure({
        clientId: process.env.COGNITO_CLIENT_ID!,
        cognitoIdpEndpoint: process.env.COGNITO_IDP_ENDPOINT!,
        location: new CustomLocation(session),
        history: { pushState: () => {} }
    });
};
```
The code works fine.

However when i create the tests for this file, i get the following error

```
 FAIL  src/lib/passwordless.spec.ts
  ● Test suite failed to run

    Cannot find module 'amazon-cognito-passwordless-auth' from 'src/lib/passwordless.spec.ts'

      3 | import { faker } from '@faker-js/faker';
      4 |
    > 5 | jest.mock('amazon-cognito-passwordless-auth', () => ({
        |      ^
      6 |     Passwordless: {
      7 |         configure: jest.fn()
      8 |     }

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/lib/passwordless.spec.ts:5:6)
```

The tsconfig file is as below:

```{
    "compilerOptions": {
        "target": "ES2020",
        "module": "ESNext",
        "rootDir": "src",
        "types": ["jest", "node"],
        "outDir": "./build",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitAny": true,
        "skipLibCheck": true,
        "moduleResolution": "node"
    },
    "include": ["src/**/*.ts", "src/**/*.json", "node_modules/@types"],
    "exclude": ["node_modules", "coverage", "src/tests"]
}```



Could you point me in a direction that would help me get tests working for this  library on nodejs.

**Comment by ottokruse** [comment]
Jest is annoying because it packs it's own module resolver, which apparently is failing here (often does). Don't know why in this particular case.

You could try specify your own moduleNameMapper with Jest. Jest offers some features for custom module resolution (that you shouldn't need, but Jest makes you need it).

**Comment by fahadsadiq** [comment]
That did the trick. Thank you for the solution :)
